export interface BillingCatalogItem {
  id: string;
  sector: string;
  service: string;
  scope: string;
  recommendedPrice: number;
  priceNote?: string;
}

export const BILLING_SERVICES_CATALOG: BillingCatalogItem[] = [
  {
    id: '3-1-consulta-inicial-remota',
    sector: '3.1 Consultoria, valoracion inicial y estrategia probatoria',
    service: 'Consulta inicial remota',
    scope: 'Reunion de hasta 45 minutos para conocer el caso y orientar sobre evidencia disponible.',
    recommendedPrice: 180000,
  },
  {
    id: '3-1-consulta-tecnica-ampliada',
    sector: '3.1 Consultoria, valoracion inicial y estrategia probatoria',
    service: 'Consulta tecnica ampliada',
    scope: 'Reunion de hasta 90 minutos, revision inicial de documentos o capturas y recomendaciones.',
    recommendedPrice: 320000,
  },
  {
    id: '3-1-concepto-viabilidad-probatoria',
    sector: '3.1 Consultoria, valoracion inicial y estrategia probatoria',
    service: 'Concepto de viabilidad probatoria',
    scope: 'Revision del caso, identificacion de fuentes digitales, riesgos y plan de recoleccion.',
    recommendedPrice: 550000,
  },
  {
    id: '3-1-reunion-abogado',
    sector: '3.1 Consultoria, valoracion inicial y estrategia probatoria',
    service: 'Reunion con abogado del cliente',
    scope: 'Analisis tecnico-juridico del alcance probatorio, hasta 90 minutos.',
    recommendedPrice: 380000,
  },
  {
    id: '3-1-evaluacion-urgente',
    sector: '3.1 Consultoria, valoracion inicial y estrategia probatoria',
    service: 'Evaluacion urgente del caso',
    scope: 'Revision prioritaria dentro de las siguientes 24 horas.',
    recommendedPrice: 850000,
  },
  {
    id: '3-2-apertura-caso',
    sector: '3.2 Recepcion, inventario y cadena de custodia',
    service: 'Apertura administrativa del caso',
    scope: 'Codigo interno, carpeta digital segura, identificacion del cliente y acta inicial.',
    recommendedPrice: 180000,
  },
  {
    id: '3-2-recepcion-evidencia-fisica',
    sector: '3.2 Recepcion, inventario y cadena de custodia',
    service: 'Recepcion de evidencia digital fisica',
    scope: 'Registro de un computador, disco, USB o celular entregado.',
    recommendedPrice: 250000,
    priceNote: 'por elemento',
  },
  {
    id: '3-2-inventario-tecnico',
    sector: '3.2 Recepcion, inventario y cadena de custodia',
    service: 'Inventario tecnico de equipo',
    scope: 'Marca, modelo, serial, caracteristicas visibles, fotografias y estado de recepcion.',
    recommendedPrice: 280000,
    priceNote: 'por equipo',
  },
  {
    id: '3-2-cadena-custodia-inicial',
    sector: '3.2 Recepcion, inventario y cadena de custodia',
    service: 'Formato de cadena de custodia inicial',
    scope: 'Registro de recepcion, embalaje, identificacion y responsables.',
    recommendedPrice: 320000,
    priceNote: 'por elemento',
  },
  {
    id: '3-2-etiquetado-embalaje',
    sector: '3.2 Recepcion, inventario y cadena de custodia',
    service: 'Etiquetado y embalaje tecnico',
    scope: 'Bolsa, sello, identificacion y registro fotografico.',
    recommendedPrice: 120000,
    priceNote: 'por elemento',
  },
  {
    id: '3-2-custodia-mensual',
    sector: '3.2 Recepcion, inventario y cadena de custodia',
    service: 'Custodia mensual de evidencia fisica',
    scope: 'Conservacion en espacio controlado, registro de acceso y trazabilidad.',
    recommendedPrice: 140000,
    priceNote: 'mensual por elemento',
  },
  {
    id: '3-2-copia-segura-evidencia',
    sector: '3.2 Recepcion, inventario y cadena de custodia',
    service: 'Copia segura de evidencia entregada',
    scope: 'Organizacion, hash y almacenamiento cifrado hasta 50 GB.',
    recommendedPrice: 280000,
  },
  {
    id: '3-3-preservacion-web',
    sector: '3.3 Preservacion tecnica de evidencia digital visible',
    service: 'Preservacion de una pagina web',
    scope: 'Captura tecnica, URL, fecha, hash y registro descriptivo.',
    recommendedPrice: 350000,
  },
  {
    id: '3-3-preservacion-redes',
    sector: '3.3 Preservacion tecnica de evidencia digital visible',
    service: 'Preservacion de redes sociales',
    scope: 'Hasta 10 publicaciones o elementos visibles de un perfil.',
    recommendedPrice: 480000,
  },
  {
    id: '3-3-preservacion-chat',
    sector: '3.3 Preservacion tecnica de evidencia digital visible',
    service: 'Preservacion de conversacion exportada',
    scope: 'Un chat entregado por el cliente, organizacion y hash de archivos.',
    recommendedPrice: 550000,
  },
  {
    id: '3-3-preservacion-correo',
    sector: '3.3 Preservacion tecnica de evidencia digital visible',
    service: 'Preservacion de correo electronico',
    scope: 'Hasta 10 correos exportados con adjuntos y metadatos disponibles.',
    recommendedPrice: 580000,
  },
  {
    id: '3-3-preservacion-archivos',
    sector: '3.3 Preservacion tecnica de evidencia digital visible',
    service: 'Preservacion de archivos digitales',
    scope: 'Hasta 25 archivos con calculo de hashes e inventario.',
    recommendedPrice: 450000,
  },
  {
    id: '3-3-paquete-internet',
    sector: '3.3 Preservacion tecnica de evidencia digital visible',
    service: 'Paquete de evidencia en internet',
    scope: 'Hasta 20 URL, capturas tecnicas, hashes e informe breve.',
    recommendedPrice: 980000,
  },
  {
    id: '3-3-preservacion-urgente',
    sector: '3.3 Preservacion tecnica de evidencia digital visible',
    service: 'Preservacion urgente por riesgo de eliminacion',
    scope: 'Ejecucion prioritaria en maximo 12 horas.',
    recommendedPrice: 560000,
    priceNote: 'precio normal + 60%',
  },
  {
    id: '3-4-imagen-usb',
    sector: '3.4 Adquisicion y copia forense de dispositivos',
    service: 'Imagen forense de memoria USB hasta 128 GB',
    scope: 'Copia bit a bit, hashes, acta tecnica y almacenamiento temporal.',
    recommendedPrice: 750000,
  },
  {
    id: '3-4-imagen-disco-externo',
    sector: '3.4 Adquisicion y copia forense de dispositivos',
    service: 'Imagen forense de disco externo hasta 1 TB',
    scope: 'Adquisicion, hashes y registro tecnico.',
    recommendedPrice: 1150000,
  },
  {
    id: '3-4-imagen-disco-interno',
    sector: '3.4 Adquisicion y copia forense de dispositivos',
    service: 'Imagen forense de disco interno hasta 1 TB',
    scope: 'Adquisicion controlada desde computador o disco retirado.',
    recommendedPrice: 1350000,
  },
  {
    id: '3-4-imagen-disco-2tb',
    sector: '3.4 Adquisicion y copia forense de dispositivos',
    service: 'Imagen forense de disco entre 1 TB y 2 TB',
    scope: 'Copia, validacion e informe de adquisicion.',
    recommendedPrice: 1750000,
  },
  {
    id: '3-4-capacidad-adicional',
    sector: '3.4 Adquisicion y copia forense de dispositivos',
    service: 'Capacidad adicional superior a 2 TB',
    scope: 'Por cada TB adicional o fraccion.',
    recommendedPrice: 420000,
  },
  {
    id: '3-4-segundo-dispositivo',
    sector: '3.4 Adquisicion y copia forense de dispositivos',
    service: 'Adquisicion de segundo dispositivo del mismo caso',
    scope: 'Aplicable si se procesa en la misma jornada.',
    recommendedPrice: 0,
    priceNote: '15% de descuento',
  },
  {
    id: '3-4-copia-urgente',
    sector: '3.4 Adquisicion y copia forense de dispositivos',
    service: 'Copia forense urgente',
    scope: 'Prioridad operativa dentro de 24 horas.',
    recommendedPrice: 1125000,
    priceNote: 'precio normal + 50%',
  },
  {
    id: '3-5-revision-basica-archivos',
    sector: '3.5 Analisis de computadores, discos y memorias',
    service: 'Revision basica de archivos entregados',
    scope: 'Hasta 50 archivos, metadatos, fechas y hashes.',
    recommendedPrice: 850000,
  },
  {
    id: '3-5-revision-ampliada-archivos',
    sector: '3.5 Analisis de computadores, discos y memorias',
    service: 'Revision ampliada de archivos',
    scope: 'Entre 51 y 500 archivos relacionados con un hecho especifico.',
    recommendedPrice: 1850000,
  },
  {
    id: '3-5-eliminacion-archivos',
    sector: '3.5 Analisis de computadores, discos y memorias',
    service: 'Analisis de eliminacion de archivos',
    scope: 'Busqueda de indicios de borrado o recuperacion en un dispositivo previamente adquirido.',
    recommendedPrice: 1900000,
    priceNote: 'desde',
  },
  {
    id: '3-5-recuperacion-basica',
    sector: '3.5 Analisis de computadores, discos y memorias',
    service: 'Recuperacion logica basica de archivos borrados',
    scope: 'Archivos recuperables sin reconstruccion compleja.',
    recommendedPrice: 1650000,
    priceNote: 'desde',
  },
  {
    id: '3-5-recuperacion-avanzada',
    sector: '3.5 Analisis de computadores, discos y memorias',
    service: 'Recuperacion avanzada',
    scope: 'Dispositivo deteriorado, multiples particiones o gran volumen de datos.',
    recommendedPrice: 3800000,
    priceNote: 'desde',
  },
  {
    id: '3-5-linea-tiempo-basica',
    sector: '3.5 Analisis de computadores, discos y memorias',
    service: 'Linea de tiempo digital basica',
    scope: 'Organizacion cronologica de eventos identificados en una fuente.',
    recommendedPrice: 1650000,
  },
  {
    id: '3-5-linea-tiempo-multiproposito',
    sector: '3.5 Analisis de computadores, discos y memorias',
    service: 'Linea de tiempo multiproposito',
    scope: 'Cruce de varias fuentes digitales o usuarios.',
    recommendedPrice: 3900000,
    priceNote: 'desde',
  },
  {
    id: '3-5-busqueda-palabras',
    sector: '3.5 Analisis de computadores, discos y memorias',
    service: 'Busqueda focalizada por palabras clave',
    scope: 'Hasta 30 criterios sobre una imagen forense existente.',
    recommendedPrice: 1250000,
  },
  {
    id: '3-5-fuga-documental',
    sector: '3.5 Analisis de computadores, discos y memorias',
    service: 'Investigacion de copia o fuga documental',
    scope: 'Documentos, USB, fechas, usuarios y correlacion inicial.',
    recommendedPrice: 4800000,
    priceNote: 'desde',
  },
  {
    id: '3-6-extraccion-un-navegador',
    sector: '3.6 Analisis de navegadores y actividad web',
    service: 'Extraccion logica de un navegador',
    scope: 'Un perfil de usuario, historial, descargas y artefactos disponibles.',
    recommendedPrice: 780000,
  },
  {
    id: '3-6-extraccion-chrome-edge',
    sector: '3.6 Analisis de navegadores y actividad web',
    service: 'Extraccion logica de Chrome y Edge',
    scope: 'Un perfil de Windows, artefactos recuperables y hashes.',
    recommendedPrice: 1250000,
  },
  {
    id: '3-6-historial-descargas',
    sector: '3.6 Analisis de navegadores y actividad web',
    service: 'Analisis de historial y descargas',
    scope: 'Interpretacion tecnica orientada a un hecho investigado.',
    recommendedPrice: 980000,
  },
  {
    id: '3-6-accesos-url',
    sector: '3.6 Analisis de navegadores y actividad web',
    service: 'Analisis de accesos a plataformas o URL especificas',
    scope: 'Cruce de fechas, URLs y descargas asociadas.',
    recommendedPrice: 1350000,
  },
  {
    id: '3-6-informe-navegacion',
    sector: '3.6 Analisis de navegadores y actividad web',
    service: 'Informe tecnico de navegacion',
    scope: 'Hallazgos, metodologia, hashes y anexos de evidencia.',
    recommendedPrice: 1450000,
  },
  {
    id: '3-6-dictamen-navegacion',
    sector: '3.6 Analisis de navegadores y actividad web',
    service: 'Dictamen pericial de actividad de navegacion',
    scope: 'Informe formal para proceso judicial sobre una fuente definida.',
    recommendedPrice: 3200000,
    priceNote: 'desde',
  },
  {
    id: '3-7-analisis-10-correos',
    sector: '3.7 Correos, documentos, chats y evidencia laboral',
    service: 'Analisis de hasta 10 correos electronicos',
    scope: 'Encabezados disponibles, adjuntos, fechas e integridad.',
    recommendedPrice: 950000,
  },
  {
    id: '3-7-buzon-5gb',
    sector: '3.7 Correos, documentos, chats y evidencia laboral',
    service: 'Analisis de buzon exportado hasta 5 GB',
    scope: 'Revision focalizada por asunto, fechas o remitentes.',
    recommendedPrice: 2400000,
    priceNote: 'desde',
  },
  {
    id: '3-7-documentos-ofimaticos',
    sector: '3.7 Correos, documentos, chats y evidencia laboral',
    service: 'Analisis de documentos ofimaticos',
    scope: 'Metadatos de hasta 30 archivos Word, PDF o Excel.',
    recommendedPrice: 980000,
  },
  {
    id: '3-7-conversacion-exportada',
    sector: '3.7 Correos, documentos, chats y evidencia laboral',
    service: 'Analisis de conversacion exportada',
    scope: 'Chat, adjuntos, secuencia temporal y hash.',
    recommendedPrice: 1150000,
  },
  {
    id: '3-7-evidencia-laboral',
    sector: '3.7 Correos, documentos, chats y evidencia laboral',
    service: 'Analisis de evidencia en caso laboral',
    scope: 'Correos, chats o documentos aportados por la parte.',
    recommendedPrice: 2800000,
    priceNote: 'desde',
  },
  {
    id: '3-7-suplantacion-fraude-basico',
    sector: '3.7 Correos, documentos, chats y evidencia laboral',
    service: 'Analisis de suplantacion o fraude digital basico',
    scope: 'Correos, mensajes y enlaces aportados.',
    recommendedPrice: 3200000,
    priceNote: 'desde',
  },
  {
    id: '3-7-contraste-documentos',
    sector: '3.7 Correos, documentos, chats y evidencia laboral',
    service: 'Contraste entre documentos o versiones',
    scope: 'Comparacion tecnica de hasta 20 documentos.',
    recommendedPrice: 1480000,
  },
  {
    id: '3-8-informe-preliminar',
    sector: '3.8 Informes y dictamenes periciales',
    service: 'Informe tecnico preliminar',
    scope: 'Describe evidencia preservada y resultados iniciales sin conclusion pericial extensa.',
    recommendedPrice: 1200000,
    priceNote: 'desde',
  },
  {
    id: '3-8-informe-completo',
    sector: '3.8 Informes y dictamenes periciales',
    service: 'Informe tecnico completo',
    scope: 'Metodologia, hallazgos, hashes, anexos y conclusiones tecnicas.',
    recommendedPrice: 2300000,
    priceNote: 'desde',
  },
  {
    id: '3-8-dictamen-basico',
    sector: '3.8 Informes y dictamenes periciales',
    service: 'Dictamen pericial basico',
    scope: 'Una fuente digital delimitada, informe formal y anexos.',
    recommendedPrice: 2900000,
    priceNote: 'desde',
  },
  {
    id: '3-8-dictamen-intermedio',
    sector: '3.8 Informes y dictamenes periciales',
    service: 'Dictamen pericial intermedio',
    scope: 'Hasta dos fuentes digitales o analisis correlacionado moderado.',
    recommendedPrice: 5500000,
    priceNote: 'desde',
  },
  {
    id: '3-8-dictamen-complejo',
    sector: '3.8 Informes y dictamenes periciales',
    service: 'Dictamen pericial complejo',
    scope: 'Varias fuentes, linea de tiempo, recuperacion o fraude corporativo.',
    recommendedPrice: 8900000,
    priceNote: 'desde',
  },
  {
    id: '3-8-dictamen-entidad-publica',
    sector: '3.8 Informes y dictamenes periciales',
    service: 'Dictamen para controversia con entidad publica',
    scope: 'Expediente tecnico para proceso administrativo o contencioso.',
    recommendedPrice: 9800000,
    priceNote: 'desde',
  },
  {
    id: '3-8-ampliacion-dictamen',
    sector: '3.8 Informes y dictamenes periciales',
    service: 'Ampliacion de dictamen',
    scope: 'Respuesta a nuevas preguntas tecnicas sin nueva adquisicion.',
    recommendedPrice: 1600000,
    priceNote: 'desde',
  },
  {
    id: '3-8-correccion-informacion-nueva',
    sector: '3.8 Informes y dictamenes periciales',
    service: 'Correccion por informacion nueva del cliente',
    scope: 'Revision adicional no atribuible al perito.',
    recommendedPrice: 0,
    priceNote: 'segun alcance',
  },
  {
    id: '3-9-lectura-critica-dictamen',
    sector: '3.9 Revision y contradiccion de dictamenes de terceros',
    service: 'Lectura critica inicial de dictamen existente',
    scope: 'Hasta 50 paginas y reunion de explicacion.',
    recommendedPrice: 850000,
  },
  {
    id: '3-9-matriz-errores',
    sector: '3.9 Revision y contradiccion de dictamenes de terceros',
    service: 'Matriz de errores metodologicos',
    scope: 'Revision de cadena de custodia, hashes, metodologia y conclusiones.',
    recommendedPrice: 1850000,
  },
  {
    id: '3-9-concepto-contradiccion',
    sector: '3.9 Revision y contradiccion de dictamenes de terceros',
    service: 'Concepto tecnico de contradiccion',
    scope: 'Documento tecnico para apoyar estrategia del abogado.',
    recommendedPrice: 2600000,
    priceNote: 'desde',
  },
  {
    id: '3-9-contradictamen-basico',
    sector: '3.9 Revision y contradiccion de dictamenes de terceros',
    service: 'Contradictamen pericial basico',
    scope: 'Revision documental y conclusion pericial propia.',
    recommendedPrice: 3900000,
    priceNote: 'desde',
  },
  {
    id: '3-9-contradictamen-replica',
    sector: '3.9 Revision y contradiccion de dictamenes de terceros',
    service: 'Contradictamen con nueva adquisicion o replica tecnica',
    scope: 'Incluye analisis sobre evidencia disponible.',
    recommendedPrice: 6500000,
    priceNote: 'desde',
  },
  {
    id: '3-9-preguntas-contrainterrogatorio',
    sector: '3.9 Revision y contradiccion de dictamenes de terceros',
    service: 'Preparacion tecnica de preguntas para contrainterrogatorio',
    scope: 'Preguntas y puntos criticos para el abogado.',
    recommendedPrice: 1200000,
  },
  {
    id: '4-1-preparacion-audiencia',
    sector: '4.1 Audiencias virtuales',
    service: 'Preparacion para audiencia de dictamen propio',
    scope: 'Revision del informe y reunion de hasta 2 horas con abogado o cliente.',
    recommendedPrice: 850000,
  },
  {
    id: '4-1-audiencia-virtual-corta',
    sector: '4.1 Audiencias virtuales',
    service: 'Audiencia virtual corta',
    scope: 'Comparecencia de hasta 2 horas para sustentar dictamen propio.',
    recommendedPrice: 1250000,
  },
  {
    id: '4-1-audiencia-virtual-extendida',
    sector: '4.1 Audiencias virtuales',
    service: 'Audiencia virtual extendida',
    scope: 'Entre 2 y 4 horas de comparecencia.',
    recommendedPrice: 2100000,
  },
  {
    id: '4-1-hora-adicional-virtual',
    sector: '4.1 Audiencias virtuales',
    service: 'Hora adicional de audiencia virtual',
    scope: 'Cobro por hora despues de las horas contratadas.',
    recommendedPrice: 420000,
    priceNote: 'por hora',
  },
  {
    id: '4-1-audiencia-contradictamen',
    sector: '4.1 Audiencias virtuales',
    service: 'Audiencia sobre contradictamen',
    scope: 'Sustentacion y contradiccion tecnica, hasta 2 horas.',
    recommendedPrice: 1600000,
  },
  {
    id: '4-1-simulacion-interrogatorio',
    sector: '4.1 Audiencias virtuales',
    service: 'Simulacion de interrogatorio previo',
    scope: 'Preparacion de respuestas y revision de puntos debiles.',
    recommendedPrice: 680000,
  },
  {
    id: '4-2-audiencia-presencial-ciudad',
    sector: '4.2 Audiencias presenciales',
    service: 'Audiencia presencial en la misma ciudad',
    scope: 'Hasta 3 horas de comparecencia; no incluye transporte.',
    recommendedPrice: 1850000,
  },
  {
    id: '4-2-media-jornada-presencial',
    sector: '4.2 Audiencias presenciales',
    service: 'Media jornada presencial',
    scope: 'Hasta 5 horas de disponibilidad.',
    recommendedPrice: 2600000,
  },
  {
    id: '4-2-jornada-completa-presencial',
    sector: '4.2 Audiencias presenciales',
    service: 'Jornada completa presencial',
    scope: 'Hasta 8 horas de disponibilidad.',
    recommendedPrice: 3800000,
  },
  {
    id: '4-2-hora-adicional-presencial',
    sector: '4.2 Audiencias presenciales',
    service: 'Hora adicional presencial',
    scope: 'Cobro por hora despues del tiempo contratado.',
    recommendedPrice: 480000,
    priceNote: 'por hora',
  },
  {
    id: '4-2-audiencia-fuera-ciudad',
    sector: '4.2 Audiencias presenciales',
    service: 'Audiencia fuera de la ciudad',
    scope: 'Jornada reservada para desplazamiento y audiencia.',
    recommendedPrice: 3900000,
    priceNote: 'desde + gastos',
  },
  {
    id: '5-plan-evidencia-inicial',
    sector: '5 Planes para personas naturales',
    service: 'Plan Evidencia Digital Inicial',
    scope: 'Consulta inicial, apertura, preservacion de hasta 10 evidencias e informe preliminar.',
    recommendedPrice: 1250000,
  },
  {
    id: '5-plan-personal-forense',
    sector: '5 Planes para personas naturales',
    service: 'Plan Caso Personal Forense',
    scope: 'Consulta ampliada, apertura, recepcion de una fuente, cadena de custodia e informe completo.',
    recommendedPrice: 3900000,
  },
  {
    id: '5-plan-pericial-audiencia',
    sector: '5 Planes para personas naturales',
    service: 'Plan Caso Personal Pericial con Audiencia Virtual',
    scope: 'Incluye plan personal forense, dictamen formal y una comparecencia virtual.',
    recommendedPrice: 5450000,
  },
  {
    id: '5-plan-fraude-suplantacion',
    sector: '5 Planes para personas naturales',
    service: 'Plan Fraude o Suplantacion Digital Personal',
    scope: 'Consulta prioritaria, preservacion, analisis de hasta dos fuentes e informe/dictamen.',
    recommendedPrice: 4800000,
    priceNote: 'desde',
  },
  {
    id: '6-plan-juridico-validacion',
    sector: '6 Planes para abogados y firmas juridicas',
    service: 'Plan Juridico 1 Validacion de Evidencia',
    scope: 'Reunion, revision de archivos, riesgos de integridad y concepto tecnico breve.',
    recommendedPrice: 1850000,
  },
  {
    id: '6-plan-juridico-dictamen',
    sector: '6 Planes para abogados y firmas juridicas',
    service: 'Plan Juridico 2 Dictamen Digital para Litigio',
    scope: 'Objeto de prueba, cadena documental, analisis principal e informe pericial formal.',
    recommendedPrice: 4900000,
    priceNote: 'desde',
  },
  {
    id: '6-plan-juridico-contradiccion',
    sector: '6 Planes para abogados y firmas juridicas',
    service: 'Plan Juridico 3 Contradiccion de Dictamen Informatico',
    scope: 'Revision de dictamen contrario, matriz tecnica y contradictamen.',
    recommendedPrice: 5800000,
    priceNote: 'desde',
  },
  {
    id: '6-plan-juridico-mensual',
    sector: '6 Planes para abogados y firmas juridicas',
    service: 'Plan Juridico Mensual Firma Aliada',
    scope: 'Consultas breves, revisiones preliminares y descuentos en dictamenes y audiencias.',
    recommendedPrice: 2400000,
    priceNote: 'mensual',
  },
  {
    id: '7-plan-empresarial-prevencion',
    sector: '7 Planes empresariales',
    service: 'Plan Empresarial 1 Prevencion y Preparacion Probatoria',
    scope: 'Diagnostico, formatos, orientacion y asesoria mensual.',
    recommendedPrice: 2600000,
    priceNote: 'mensual',
  },
  {
    id: '7-plan-empresarial-investigacion',
    sector: '7 Planes empresariales',
    service: 'Plan Empresarial 2 Investigacion Interna Focalizada',
    scope: 'Planeacion, recepcion de fuentes, analisis y reportes ejecutivo/tecnico.',
    recommendedPrice: 6800000,
    priceNote: 'por caso, desde',
  },
  {
    id: '7-plan-empresarial-fraude-fuga',
    sector: '7 Planes empresariales',
    service: 'Plan Empresarial 3 Fraude o Fuga de Informacion',
    scope: 'Atencion prioritaria, hasta tres fuentes y dictamen con reunion ejecutiva.',
    recommendedPrice: 10800000,
    priceNote: 'por caso, desde',
  },
  {
    id: '7-plan-empresarial-litigio',
    sector: '7 Planes empresariales',
    service: 'Plan Empresarial 4 Litigio Corporativo Integral',
    scope: 'Planeacion con juridico, analisis forense focalizado y audiencia virtual incluida.',
    recommendedPrice: 14900000,
    priceNote: 'desde',
  },
  {
    id: '7-plan-empresarial-mensual-prioritario',
    sector: '7 Planes empresariales',
    service: 'Plan Empresarial Mensual Respuesta Forense Prioritaria',
    scope: 'Disponibilidad prioritaria, 8 horas mensuales y activacion ante incidentes.',
    recommendedPrice: 4800000,
    priceNote: 'mensual',
  },
  {
    id: '8-concepto-preliminar-entidad',
    sector: '8 Servicios para entidades publicas o procesos administrativos',
    service: 'Concepto tecnico preliminar para entidad o contratista',
    scope: 'Concepto inicial para contratacion o evaluacion institucional.',
    recommendedPrice: 3500000,
    priceNote: 'desde',
  },
  {
    id: '8-dictamen-administrativo-sencillo',
    sector: '8 Servicios para entidades publicas o procesos administrativos',
    service: 'Dictamen pericial administrativo sencillo',
    scope: 'Dictamen para proceso administrativo con alcance delimitado.',
    recommendedPrice: 5800000,
    priceNote: 'desde',
  },
  {
    id: '8-dictamen-controversia-contractual',
    sector: '8 Servicios para entidades publicas o procesos administrativos',
    service: 'Dictamen tecnico para controversia contractual o administrativa',
    scope: 'Expediente tecnico con alcance contencioso-administrativo.',
    recommendedPrice: 9800000,
    priceNote: 'desde',
  },
  {
    id: '8-peritaje-complejo-multiples-fuentes',
    sector: '8 Servicios para entidades publicas o procesos administrativos',
    service: 'Peritaje complejo con multiples fuentes digitales',
    scope: 'Peritaje con fuentes diversas y anexos avanzados.',
    recommendedPrice: 15000000,
    priceNote: 'desde',
  },
  {
    id: '8-investigacion-extensa-audiencia',
    sector: '8 Servicios para entidades publicas o procesos administrativos',
    service: 'Investigacion tecnica extensa con audiencia',
    scope: 'Incluye anexos especializados y sustentacion.',
    recommendedPrice: 25000000,
    priceNote: 'desde',
  },
  {
    id: '9-cronologia-visual',
    sector: '9 Servicios adicionales comercializables',
    service: 'Elaboracion de cronologia visual del caso',
    scope: 'Construccion visual de hitos y secuencia de eventos del caso.',
    recommendedPrice: 650000,
    priceNote: 'desde',
  },
  {
    id: '9-organizacion-anexos-abogado',
    sector: '9 Servicios adicionales comercializables',
    service: 'Organizacion de anexos para abogado',
    scope: 'Ordenamiento tecnico de anexos para sustentacion juridica.',
    recommendedPrice: 480000,
    priceNote: 'desde',
  },
  {
    id: '9-copia-adicional-cifrada',
    sector: '9 Servicios adicionales comercializables',
    service: 'Copia adicional cifrada de evidencia',
    scope: 'Copia adicional cifrada hasta 50 GB.',
    recommendedPrice: 220000,
  },
  {
    id: '9-almacenamiento-adicional',
    sector: '9 Servicios adicionales comercializables',
    service: 'Almacenamiento digital seguro adicional',
    scope: 'Cobro mensual por cada 100 GB adicionales.',
    recommendedPrice: 90000,
    priceNote: 'mensual por 100 GB',
  },
  {
    id: '9-informe-ejecutivo-gerencia',
    sector: '9 Servicios adicionales comercializables',
    service: 'Informe ejecutivo para gerencia',
    scope: 'Resumen ejecutivo para toma de decisiones.',
    recommendedPrice: 750000,
    priceNote: 'desde',
  },
  {
    id: '9-capacitacion-empresarial',
    sector: '9 Servicios adicionales comercializables',
    service: 'Capacitacion empresarial de 2 horas sobre evidencia digital',
    scope: 'Sesion para equipos empresariales.',
    recommendedPrice: 1200000,
  },
  {
    id: '9-capacitacion-abogados',
    sector: '9 Servicios adicionales comercializables',
    service: 'Capacitacion para abogados sobre prueba digital y peritaje',
    scope: 'Sesion tecnica para firmas juridicas.',
    recommendedPrice: 1450000,
  },
  {
    id: '9-revision-protocolo-cadena',
    sector: '9 Servicios adicionales comercializables',
    service: 'Revision de protocolo interno de cadena de custodia',
    scope: 'Evaluacion tecnica de protocolo interno vigente.',
    recommendedPrice: 1800000,
    priceNote: 'desde',
  },
  {
    id: '9-diseno-procedimiento-preservacion',
    sector: '9 Servicios adicionales comercializables',
    service: 'Diseno de procedimiento interno de preservacion de evidencia',
    scope: 'Diseno e implementacion documental inicial.',
    recommendedPrice: 2800000,
    priceNote: 'desde',
  },
  {
    id: '9-atencion-urgente-24h',
    sector: '9 Servicios adicionales comercializables',
    service: 'Atencion urgente en menos de 24 horas',
    scope: 'Activacion prioritaria del servicio solicitado.',
    recommendedPrice: 500000,
    priceNote: 'recargo del 50%',
  },
  {
    id: '9-atencion-nocturna-festivo',
    sector: '9 Servicios adicionales comercializables',
    service: 'Atencion nocturna, fin de semana o festivo',
    scope: 'Disponibilidad fuera de horario ordinario.',
    recommendedPrice: 400000,
    priceNote: 'recargo del 40%',
  },
  {
    id: '10-publico-consulta-inicial',
    sector: '10 Tabla resumida para web (desde)',
    service: 'Consulta inicial de evidencia digital',
    scope: 'Tarifa comercial resumida para publicacion web.',
    recommendedPrice: 180000,
    priceNote: 'desde',
  },
  {
    id: '10-publico-preservacion-visible',
    sector: '10 Tabla resumida para web (desde)',
    service: 'Preservacion de evidencia digital visible',
    scope: 'Tarifa comercial resumida para publicacion web.',
    recommendedPrice: 350000,
    priceNote: 'desde',
  },
  {
    id: '10-publico-analisis-correos',
    sector: '10 Tabla resumida para web (desde)',
    service: 'Analisis de correos, chats o documentos',
    scope: 'Tarifa comercial resumida para publicacion web.',
    recommendedPrice: 950000,
    priceNote: 'desde',
  },
  {
    id: '10-publico-analisis-navegadores',
    sector: '10 Tabla resumida para web (desde)',
    service: 'Analisis de navegadores y actividad web',
    scope: 'Tarifa comercial resumida para publicacion web.',
    recommendedPrice: 780000,
    priceNote: 'desde',
  },
  {
    id: '10-publico-recuperacion-borrados',
    sector: '10 Tabla resumida para web (desde)',
    service: 'Recuperacion o analisis de archivos borrados',
    scope: 'Tarifa comercial resumida para publicacion web.',
    recommendedPrice: 1650000,
    priceNote: 'desde',
  },
  {
    id: '10-publico-imagen-forense',
    sector: '10 Tabla resumida para web (desde)',
    service: 'Imagen forense de dispositivo',
    scope: 'Tarifa comercial resumida para publicacion web.',
    recommendedPrice: 750000,
    priceNote: 'desde',
  },
  {
    id: '10-publico-informe-completo',
    sector: '10 Tabla resumida para web (desde)',
    service: 'Informe tecnico completo',
    scope: 'Tarifa comercial resumida para publicacion web.',
    recommendedPrice: 2300000,
    priceNote: 'desde',
  },
  {
    id: '10-publico-dictamen-pericial',
    sector: '10 Tabla resumida para web (desde)',
    service: 'Dictamen pericial digital',
    scope: 'Tarifa comercial resumida para publicacion web.',
    recommendedPrice: 2900000,
    priceNote: 'desde',
  },
  {
    id: '10-publico-contradictamen',
    sector: '10 Tabla resumida para web (desde)',
    service: 'Contradictamen informatico',
    scope: 'Tarifa comercial resumida para publicacion web.',
    recommendedPrice: 3900000,
    priceNote: 'desde',
  },
  {
    id: '10-publico-investigacion-empresarial',
    sector: '10 Tabla resumida para web (desde)',
    service: 'Investigacion empresarial',
    scope: 'Tarifa comercial resumida para publicacion web.',
    recommendedPrice: 6800000,
    priceNote: 'desde',
  },
  {
    id: '10-publico-litigio-corporativo',
    sector: '10 Tabla resumida para web (desde)',
    service: 'Litigio corporativo integral',
    scope: 'Tarifa comercial resumida para publicacion web.',
    recommendedPrice: 14900000,
    priceNote: 'desde',
  },
  {
    id: '10-publico-audiencia-virtual',
    sector: '10 Tabla resumida para web (desde)',
    service: 'Audiencia virtual',
    scope: 'Tarifa comercial resumida para publicacion web.',
    recommendedPrice: 1250000,
    priceNote: 'desde',
  },
  {
    id: '10-publico-audiencia-presencial',
    sector: '10 Tabla resumida para web (desde)',
    service: 'Audiencia presencial',
    scope: 'Tarifa comercial resumida para publicacion web.',
    recommendedPrice: 1850000,
    priceNote: 'desde',
  },
  {
    id: '10-publico-entidades-publicas',
    sector: '10 Tabla resumida para web (desde)',
    service: 'Servicios para entidades publicas',
    scope: 'Tarifa comercial resumida para publicacion web.',
    recommendedPrice: 0,
    priceNote: 'cotizacion segun alcance',
  },
  {
    id: '11-plan-lanzamiento-evidencia-inicial',
    sector: '11 Paquetes comerciales recomendados para lanzar',
    service: 'Paquete lanzamiento Persona natural Evidencia Digital Inicial',
    scope: 'Plan comercial sugerido para lanzamiento.',
    recommendedPrice: 1250000,
  },
  {
    id: '11-plan-lanzamiento-caso-pericial',
    sector: '11 Paquetes comerciales recomendados para lanzar',
    service: 'Paquete lanzamiento Persona natural Caso Personal Pericial',
    scope: 'Plan comercial sugerido para lanzamiento.',
    recommendedPrice: 5450000,
  },
  {
    id: '11-plan-lanzamiento-dictamen-litigo',
    sector: '11 Paquetes comerciales recomendados para lanzar',
    service: 'Paquete lanzamiento Abogados Dictamen Digital para Litigio',
    scope: 'Plan comercial sugerido para lanzamiento.',
    recommendedPrice: 4900000,
    priceNote: 'desde',
  },
  {
    id: '11-plan-lanzamiento-contradiccion',
    sector: '11 Paquetes comerciales recomendados para lanzar',
    service: 'Paquete lanzamiento Abogados Contradiccion de Dictamen',
    scope: 'Plan comercial sugerido para lanzamiento.',
    recommendedPrice: 5800000,
    priceNote: 'desde',
  },
  {
    id: '11-plan-lanzamiento-investigacion',
    sector: '11 Paquetes comerciales recomendados para lanzar',
    service: 'Paquete lanzamiento Empresas Investigacion Interna Focalizada',
    scope: 'Plan comercial sugerido para lanzamiento.',
    recommendedPrice: 6800000,
    priceNote: 'desde',
  },
  {
    id: '11-plan-lanzamiento-litigio-integral',
    sector: '11 Paquetes comerciales recomendados para lanzar',
    service: 'Paquete lanzamiento Empresas Litigio Corporativo Integral',
    scope: 'Plan comercial sugerido para lanzamiento.',
    recommendedPrice: 14900000,
    priceNote: 'desde',
  },
];
